# Generated by Django 2.1.2 on 2018-10-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0003_auto_20181025_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
